# this number cannot be higher than 2,000,000 by any means unless an additional thread is spawned
# increased from default size to allow for some larger pre-allocations.
array-size-threshold = 1000000
